/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tec.proyecto3;

import javax.swing.JFrame;

/**
 *
 * @author usuario
 */
public class Categorias extends javax.swing.JPanel {

    /**
     * Creates new form Categorias
     */
    public Categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReciclable = new javax.swing.JButton();
        btnNoReciclable = new javax.swing.JButton();
        panelCategorias = new javax.swing.JPanel();
        lblNombreCate = new javax.swing.JLabel();
        btnSalirCate = new javax.swing.JButton();

        btnReciclable.setText("Reciclable");
        btnReciclable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciclableActionPerformed(evt);
            }
        });

        btnNoReciclable.setText("No Reciclable");
        btnNoReciclable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoReciclableActionPerformed(evt);
            }
        });

        panelCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNombreCate.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNombreCate.setText("Nombre:");

        btnSalirCate.setText("Salir");

        javax.swing.GroupLayout panelCategoriasLayout = new javax.swing.GroupLayout(panelCategorias);
        panelCategorias.setLayout(panelCategoriasLayout);
        panelCategoriasLayout.setHorizontalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 553, Short.MAX_VALUE)
                .addComponent(btnSalirCate)
                .addContainerGap())
        );
        panelCategoriasLayout.setVerticalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCate)
                    .addComponent(btnSalirCate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnReciclable, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnNoReciclable, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReciclable, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoReciclable, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoReciclableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoReciclableActionPerformed
        JFrame nuevaVentana = new JFrame("SubCategorías");

    // Configurar el nuevo JFrame
        nuevaVentana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nuevaVentana.setSize(745, 430);
        nuevaVentana.setLocationRelativeTo(null);

        // Agregar el panel SubCategorias al nuevo JFrame
        nuevaVentana.setContentPane(new SubCategorias());

        // Hacer visible la nueva ventana
        nuevaVentana.setVisible(true);

        // Cerrar la ventana actual (JFrame que contiene el panel Categorias)
        JFrame ventanaActual = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        ventanaActual.dispose();
    }//GEN-LAST:event_btnNoReciclableActionPerformed

    private void btnReciclableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciclableActionPerformed
        JFrame nuevaVentana = new JFrame("SubCategorías");

    // Configurar el nuevo JFrame
        nuevaVentana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        nuevaVentana.setSize(745, 430);
        nuevaVentana.setLocationRelativeTo(null);

        // Agregar el panel SubCategorias al nuevo JFrame
        nuevaVentana.setContentPane(new SubCategorias());

        // Hacer visible la nueva ventana
        nuevaVentana.setVisible(true);

        // Cerrar la ventana actual (JFrame que contiene el panel Categorias)
        JFrame ventanaActual = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        ventanaActual.dispose();
    }//GEN-LAST:event_btnReciclableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoReciclable;
    private javax.swing.JButton btnReciclable;
    private javax.swing.JButton btnSalirCate;
    private javax.swing.JLabel lblNombreCate;
    private javax.swing.JPanel panelCategorias;
    // End of variables declaration//GEN-END:variables
}
