package tec.proyecto3;

/**
 *
 * @author allaj
 */
public enum CODIGOS_ERROR {
    NOMBRE_VACIO, APELLIDO_VACIO, CORREO_VACIO, CORREO_REQUISITOS, CONTRA_VACIA, CONTRA_LONGITUD, CONTRA_REQUISITOS, SUBCATEGORIA_REQUISITOS
}
